In [1]:
import fastf1
import pandas as pd

session = fastf1.get_session(2023, "Bahrain", "R")
session.load()

lap = session.laps.pick_driver("PER")
telemetry = lap.get_telemetry()

req         WARNING 	DEFAULT CACHE ENABLED! (339.66 MB) C:\Users\DELL\AppData\Local\Temp\fastf1
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_infox - Race [v3.7.0]

driver_infoox - Race [v3.7.0]


req            INFO 	Using cached data for session_status_data
lap_counttatus_data

req            INFO 	Using cached data for track_status_data
_extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...ing_app_data

req            INFO 	Using cached data for car_datapp_data


position_datata



req            INFO 	Using cached data for weather_data
race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '55', '44', '18', '63', '77', '10', '23', '22', '2', '20', '21', '27', '24', '4', '31', '16', '81']
D:\f1_ser\.venv\Lib\site-packages\fastf1\core.py:3081: FutureWarning: pick_driver is deprecated and will be removed in a future release. Use pick_drivers instead.', '16', '81']

  warnings.warn(("pick_driver is deprecated and will be removed"

In [2]:
df = pd.DataFrame(telemetry)
df

,Date,SessionTime,DriverAhead,DistanceToDriverAhead,Time,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Distance,RelativeDistance,Status,X,Y,Z
2,2023-03-05 15:03:38.501,0 days 01:02:36.652000,,0.077778,0 days 00:00:00,9490.666735,0.000000,1,14.000000,False,1,interpolation,-0.003026,-9.908385e-09,OnTrack,-280.004244,3574.987429,-157.000373
3,2023-03-05 15:03:38.611,0 days 01:02:36.762000,,0.077778,0 days 00:00:00.110000,9432.000000,0.000000,1,14.000000,False,1,car,0.000000,0.000000e+00,OnTrack,-280.004402,3574.986957,-157.000387
4,2023-03-05 15:03:38.686,0 days 01:02:36.837000,,0.077778,0 days 00:00:00.185000,9400.124973,0.000000,1,14.000000,False,1,pos,0.004833,1.582225e-08,OnTrack,-280.000000,3575.000000,-157.000000
5,2023-03-05 15:03:38.811,0 days 01:02:36.962000,,0.077778,0 days 00:00:00.310000,9347.000000,0.000000,1,14.000000,False,1,car,0.000000,0.000000e+00,OnTrack,-279.984731,3575.045238,-156.998658
6,2023-03-05 15:03:38.946,0 days 01:02:37.097000,,0.077778,0 days 00:00:00.445000,8604.501056,0.000000,1,15.446427,False,1,pos,-0.060010,-1.964666e-07,OnTrack,-280.000000,3575.000000,-157.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42470,2023-03-05 16:37:47.109,0 days 02:36:45.260000,,705.602778,0 days 01:34:08.608000,10186.000000,258.000000,7,0.000000,False,0,car,305417.659722,9.999004e-01,OnTrack,-396.154729,945.104860,-158.999994
42471,2023-03-05 16:37:47.265,0 days 02:36:45.416000,,705.602778,0 days 01:34:08.764000,9871.075000,252.150000,7,0.000000,False,0,pos,305428.581408,9.999362e-01,OnTrack,-390.000000,1067.000000,-159.000000
42472,2023-03-05 16:37:47.269,0 days 02:36:45.420000,,705.602778,0 days 01:34:08.768000,9863.000000,252.000000,7,0.000000,False,0,car,305428.859722,9.999371e-01,OnTrack,-389.800590,1071.093669,-159.000000
42473,2023-03-05 16:37:47.445,0 days 02:36:45.596000,,705.602778,0 days 01:34:08.944000,9795.501808,249.476703,7,0.000000,False,0,pos,305441.028342,9.999769e-01,OnTrack,-380.000000,1276.000000,-159.000000
42474,2023-03-05 16:37:47.455,0 days 02:36:45.606000,,705.602778,0 days 01:34:08.954000,9791.666634,249.333332,7,0.000000,False,0,interpolation,305441.715217,9.999792e-01,OnTrack,-379.505209,1286.355956,-159.000000

In [3]:
df.drop(columns=["DriverAhead","DistanceToDriverAhead","Status","DRS","Source"],inplace=True)
df['Time_sec'] = df['Time'].dt.total_seconds()
df['Speed'] = df['Speed'].round(2)
df["X"] = df["X"].round(3)
df["Y"] = df["Y"].round(3)
df["Z"] = df["Z"].round(3)
df['RPM'] = df["RPM"].round(3)
df['Distance'] = df["Distance"].round(3)
df.drop(columns='Time',inplace=True)

In [4]:
df

,Date,SessionTime,RPM,Speed,nGear,Throttle,Brake,Distance,RelativeDistance,X,Y,Z,Time_sec
2,2023-03-05 15:03:38.501,0 days 01:02:36.652000,9490.667,0.00,1,14.000000,False,-0.003,-9.908385e-09,-280.004,3574.987,-157.000,0.000
3,2023-03-05 15:03:38.611,0 days 01:02:36.762000,9432.000,0.00,1,14.000000,False,0.000,0.000000e+00,-280.004,3574.987,-157.000,0.110
4,2023-03-05 15:03:38.686,0 days 01:02:36.837000,9400.125,0.00,1,14.000000,False,0.005,1.582225e-08,-280.000,3575.000,-157.000,0.185
5,2023-03-05 15:03:38.811,0 days 01:02:36.962000,9347.000,0.00,1,14.000000,False,0.000,0.000000e+00,-279.985,3575.045,-156.999,0.310
6,2023-03-05 15:03:38.946,0 days 01:02:37.097000,8604.501,0.00,1,15.446427,False,-0.060,-1.964666e-07,-280.000,3575.000,-157.000,0.445
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42470,2023-03-05 16:37:47.109,0 days 02:36:45.260000,10186.000,258.00,7,0.000000,False,305417.660,9.999004e-01,-396.155,945.105,-159.000,5648.608
42471,2023-03-05 16:37:47.265,0 days 02:36:45.416000,9871.075,252.15,7,0.000000,False,305428.581,9.999362e-01,-390.000,1067.000,-159.000,5648.764
42472,2023-03-05 16:37:47.269,0 days 02:36:45.420000,9863.000,252.00,7,0.000000,False,305428.860,9.999371e-01,-389.801,1071.094,-159.000,5648.768
42473,2023-03-05 16:37:47.445,0 days 02:36:45.596000,9795.502,249.48,7,0.000000,False,305441.028,9.999769e-01,-380.000,1276.000,-159.000,5648.944
42474,2023-03-05 16:37:47.455,0 days 02:36:45.606000,9791.667,249.33,7,0.000000,False,305441.715,9.999792e-01,-379.505,1286.356,-159.000,5648.954

In [5]:
data = df[["Time_sec", "X", "Y", "Speed"]].to_dict(orient="records")
data

[{'Time_sec': 0.0, 'X': -280.004, 'Y': 3574.987, 'Speed': 0.0},
 {'Time_sec': 0.11, 'X': -280.004, 'Y': 3574.987, 'Speed': 0.0},
 {'Time_sec': 0.185, 'X': -280.0, 'Y': 3575.0, 'Speed': 0.0},
 {'Time_sec': 0.31, 'X': -279.985, 'Y': 3575.045, 'Speed': 0.0},
 {'Time_sec': 0.445, 'X': -280.0, 'Y': 3575.0, 'Speed': 0.0},
 {'Time_sec': 0.545, 'X': -280.0, 'Y': 3575.0, 'Speed': 0.0},
 {'Time_sec': 0.59, 'X': -279.877, 'Y': 3575.363, 'Speed': 0.0},
 {'Time_sec': 0.764, 'X': -279.0, 'Y': 3579.0, 'Speed': 6.77},
 {'Time_sec': 0.95, 'X': -279.008, 'Y': 3585.49, 'Speed': 14.0},
 {'Time_sec': 1.124, 'X': -279.0, 'Y': 3594.0, 'Speed': 18.35},
 {'Time_sec': 1.19, 'X': -278.74, 'Y': 3597.877, 'Speed': 20.0},
 {'Time_sec': 1.325, 'X': -278.0, 'Y': 3607.0, 'Speed': 25.06},
 {'Time_sec': 1.35, 'X': -277.885, 'Y': 3608.883, 'Speed': 26.0},
 {'Time_sec': 1.55, 'X': -277.151, 'Y': 3626.912, 'Speed': 32.0},
 {'Time_sec': 1.585, 'X': -277.0, 'Y': 3631.0, 'Speed': 33.25},
 {'Time_sec': 1.83, 'X': -275.595, 'Y': 3667.972, 'Speed': 42.0},
 {'Time_sec': 1.965, 'X': -275.0, 'Y': 3687.0, 'Speed': 45.37},
 {'Time_sec': 1.99, 'X': -274.927, 'Y': 3690.015, 'Speed': 46.0},
 {'Time_sec': 2.19, 'X': -274.757, 'Y': 3708.483, 'Speed': 52.0},
 {'Time_sec': 2.385, 'X': -274.0, 'Y': 3731.0, 'Speed': 59.31},
 {'Time_sec': 2.51, 'X': -272.714, 'Y': 3753.336, 'Speed': 64.0},
 {'Time_sec': 2.585, 'X': -272.0, 'Y': 3768.0, 'Speed': 67.44},
 {'Time_sec': 2.75, 'X': -271.081, 'Y': 3800.871, 'Speed': 75.0},
 {'Time_sec': 2.765, 'X': -271.0, 'Y': 3804.0, 'Speed': 75.37},
 {'Time_sec': 2.91, 'X': -270.074, 'Y': 3835.846, 'Speed': 79.0},
 {'Time_sec': 3.025, 'X': -269.0, 'Y': 3863.0, 'Speed': 84.75},
 {'Time_sec': 3.15, 'X': -267.422, 'Y': 3894.164, 'Speed': 91.0},
 {'Time_sec': 3.185, 'X': -267.0, 'Y': 3903.0, 'Speed': 92.42},
 {'Time_sec': 3.385, 'X': -265.0, 'Y': 3957.0, 'Speed': 100.55},
 {'Time_sec': 3.47, 'X': -264.087, 'Y': 3986.88, 'Speed': 104.0},
 {'Time_sec': 3.63, 'X': -262.185, 'Y': 4048.755, 'Speed': 112.0},
 {'Time_sec': 3.645, 'X': -262.0, 'Y': 4054.0, 'Speed': 112.47},
 {'Time_sec': 3.79, 'X': -260.154, 'Y': 4098.788, 'Speed': 117.0},
 {'Time_sec': 4.029, 'X': -257.177, 'Y': 4166.523, 'Speed': 133.0},
 {'Time_sec': 4.045, 'X': -257.0, 'Y': 4172.0, 'Speed': 133.66},
 {'Time_sec': 4.225, 'X': -255.0, 'Y': 4241.0, 'Speed': 141.13},
 {'Time_sec': 4.27, 'X': -254.338, 'Y': 4259.176, 'Speed': 143.0},
 {'Time_sec': 4.405, 'X': -252.0, 'Y': 4315.0, 'Speed': 150.12},
 {'Time_sec': 4.63, 'X': -248.095, 'Y': 4412.889, 'Speed': 162.0},
 {'Time_sec': 4.705, 'X': -247.0, 'Y': 4447.0, 'Speed': 165.0},
 {'Time_sec': 4.83, 'X': -245.463, 'Y': 4505.145, 'Speed': 170.0},
 {'Time_sec': 4.865, 'X': -245.0, 'Y': 4521.0, 'Speed': 171.17},
 {'Time_sec': 5.07, 'X': -241.365, 'Y': 4618.278, 'Speed': 178.0},
 {'Time_sec': 5.085, 'X': -241.0, 'Y': 4628.0, 'Speed': 178.64},
 {'Time_sec': 5.325, 'X': -234.0, 'Y': 4825.0, 'Speed': 188.93},
 {'Time_sec': 5.35, 'X': -233.398, 'Y': 4843.118, 'Speed': 190.0},
 {'Time_sec': 5.55, 'X': -230.155, 'Y': 4952.19, 'Speed': 196.0},
 {'Time_sec': 5.745, 'X': -228.0, 'Y': 5024.0, 'Speed': 202.09},
 {'Time_sec': 6.03, 'X': -224.24, 'Y': 5114.025, 'Speed': 211.0},
 {'Time_sec': 6.105, 'X': -223.0, 'Y': 5149.0, 'Speed': 212.41},
 {'Time_sec': 6.19, 'X': -221.435, 'Y': 5198.053, 'Speed': 214.0},
 {'Time_sec': 6.265, 'X': -220.0, 'Y': 5245.0, 'Speed': 215.88},
 {'Time_sec': 6.51, 'X': -215.269, 'Y': 5395.92, 'Speed': 222.0},
 {'Time_sec': 6.565, 'X': -214.0, 'Y': 5430.0, 'Speed': 223.18},
 {'Time_sec': 6.645, 'X': -212.0, 'Y': 5480.0, 'Speed': 224.89},
 {'Time_sec': 6.79, 'X': -208.679, 'Y': 5572.732, 'Speed': 228.0},
 {'Time_sec': 6.925, 'X': -206.0, 'Y': 5659.0, 'Speed': 231.75},
 {'Time_sec': 7.085, 'X': -203.0, 'Y': 5764.0, 'Speed': 236.19},
 {'Time_sec': 7.15, 'X': -201.385, 'Y': 5816.766, 'Speed': 238.0},
 {'Time_sec': 7.404, 'X': -194.0, 'Y': 6046.0, 'Speed': 241.17},
 {'Time_sec': 7.47, 'X': -192.647, 'Y': 6089.454, 'Speed': 242.0},
 {'Time_sec': 7.804, 'X': -188.0, 'Y': 6253.0, 'Speed': 249.51},
 {'Time_sec': 7.87, 'X': -186.618, 'Y': 6301.178, 'Speed': 251.0},
 {'Time_sec': 7.985, 'X': -184.0, 'Y': 6393.0, 'Speed': 252.44},
 {'Time_sec': 8.11, 'X': -181.539, 'Y': 6483.414, 'Speed': 254.0},
 {'Time_sec': 8.245, 'X': -179.0, 'Y': 6577.0, 'Speed': 253.33},
 {'Time_sec': 8.345, 'X': -177.0, 'Y': 6648.0, 'Speed': 252.82},
 {'Time_sec': 8.51, 'X': -174.331, 'Y': 6750.967, 'Speed': 252.0},
 {'Time_sec': 8.665, 'X': -172.0, 'Y': 6845.0, 'Speed': 248.12},
 {'Time_sec': 8.67, 'X': -171.918, 'Y': 6848.229, 'Speed': 248.0},
 {'Time_sec': 8.885, 'X': -168.0, 'Y': 6995.0, 'Speed': 244.93},
 {'Time_sec': 8.95, 'X': -166.704, 'Y': 7039.365, 'Speed': 244.0},
 {'Time_sec': 8.985, 'X': -166.0, 'Y': 7063.0, 'Speed': 243.12},
 {'Time_sec': 9.11, 'X': -163.506, 'Y': 7145.733, 'Speed': 240.0},
 {'Time_sec': 9.185, 'X': -162.0, 'Y': 7194.0, 'Speed': 234.56},
 {'Time_sec': 9.51, 'X': -155.309, 'Y': 7390.447, 'Speed': 211.0},
 {'Time_sec': 9.525, 'X': -155.0, 'Y': 7399.0, 'Speed': 210.25},
 {'Time_sec': 9.665, 'X': -152.0, 'Y': 7479.0, 'Speed': 203.25},
 {'Time_sec': 9.71, 'X': -150.872, 'Y': 7507.153, 'Speed': 201.0},
 {'Time_sec': 9.925, 'X': -145.0, 'Y': 7645.0, 'Speed': 180.4},
 {'Time_sec': 9.95, 'X': -144.44, 'Y': 7657.786, 'Speed': 178.0},
 {'Time_sec': 10.19, 'X': -140.49, 'Y': 7743.097, 'Speed': 163.0},
 {'Time_sec': 10.305, 'X': -138.0, 'Y': 7788.0, 'Speed': 154.95},
 {'Time_sec': 10.39, 'X': -135.572, 'Y': 7829.17, 'Speed': 149.0},
 {'Time_sec': 10.565, 'X': -130.0, 'Y': 7918.0, 'Speed': 139.45},
 {'Time_sec': 10.83, 'X': -123.861, 'Y': 7994.314, 'Speed': 125.0},
 {'Time_sec': 10.965, 'X': -119.0, 'Y': 8029.0, 'Speed': 121.14},
 {'Time_sec': 11.065, 'X': -114.0, 'Y': 8059.0, 'Speed': 118.29},
 {'Time_sec': 11.11, 'X': -111.667, 'Y': 8072.472, 'Speed': 117.0},
 {'Time_sec': 11.265, 'X': -103.0, 'Y': 8117.0, 'Speed': 113.12},
 {'Time_sec': 11.31, 'X': -99.994, 'Y': 8129.201, 'Speed': 112.0},
 {'Time_sec': 11.51, 'X': -84.059, 'Y': 8179.089, 'Speed': 103.0},
 {'Time_sec': 11.545, 'X': -81.0, 'Y': 8187.0, 'Speed': 101.1},
 {'Time_sec': 11.705, 'X': -64.0, 'Y': 8222.0, 'Speed': 92.44},
 {'Time_sec': 11.75, 'X': -56.435, 'Y': 8233.28, 'Speed': 90.0},
 {'Time_sec': 12.005, 'X': -2.0, 'Y': 8299.0, 'Speed': 81.23},
 {'Time_sec': 12.07, 'X': 6.249, 'Y': 8308.376, 'Speed': 79.0},
 {'Time_sec': 12.365, 'X': 33.0, 'Y': 8324.0, 'Speed': 69.41},
 {'Time_sec': 12.47, 'X': 59.934, 'Y': 8334.201, 'Speed': 66.0},
 {'Time_sec': 12.585, 'X': 90.0, 'Y': 8345.0, 'Speed': 63.54},
 {'Time_sec': 12.75, 'X': 109.451, 'Y': 8349.987, 'Speed': 60.0},
 {'Time_sec': 12.925, 'X': 126.0, 'Y': 8346.0, 'Speed': 58.91},
 {'Time_sec': 13.07, 'X': 158.351, 'Y': 8338.993, 'Speed': 58.0},
 {'Time_sec': 13.205, 'X': 191.0, 'Y': 8331.0, 'Speed': 58.0},
 {'Time_sec': 13.47, 'X': 228.995, 'Y': 8315.231, 'Speed': 58.0},
 {'Time_sec': 13.71, 'X': 255.843, 'Y': 8294.681, 'Speed': 60.0},
 {'Time_sec': 13.725, 'X': 258.0, 'Y': 8293.0, 'Speed': 60.37},
 {'Time_sec': 13.87, 'X': 281.759, 'Y': 8274.338, 'Speed': 64.0},
 {'Time_sec': 14.03, 'X': 310.153, 'Y': 8251.721, 'Speed': 66.0},
 {'Time_sec': 14.124, 'X': 322.0, 'Y': 8242.0, 'Speed': 68.82},
 {'Time_sec': 14.23, 'X': 330.518, 'Y': 8234.628, 'Speed': 72.0},
 {'Time_sec': 14.404, 'X': 346.0, 'Y': 8219.0, 'Speed': 75.48},
 {'Time_sec': 14.43, 'X': 350.365, 'Y': 8214.525, 'Speed': 76.0},
 {'Time_sec': 14.67, 'X': 412.455, 'Y': 8150.525, 'Speed': 85.0},
 {'Time_sec': 14.785, 'X': 436.0, 'Y': 8126.0, 'Speed': 86.92},
 {'Time_sec': 14.91, 'X': 449.102, 'Y': 8111.983, 'Speed': 89.0},
 {'Time_sec': 15.065, 'X': 462.0, 'Y': 8098.0, 'Speed': 98.3},
 {'Time_sec': 15.11, 'X': 468.708, 'Y': 8090.946, 'Speed': 101.0},
 {'Time_sec': 15.245, 'X': 495.0, 'Y': 8064.0, 'Speed': 108.59},
 {'Time_sec': 15.27, 'X': 500.328, 'Y': 8058.746, 'Speed': 110.0},
 {'Time_sec': 15.55, 'X': 567.663, 'Y': 7998.251, 'Speed': 119.0},
 {'Time_sec': 15.585, 'X': 577.0, 'Y': 7991.0, 'Speed': 119.7},
 {'Time_sec': 15.765, 'X': 628.0, 'Y': 7956.0, 'Speed': 123.3},
 {'Time_sec': 15.95, 'X': 684.801, 'Y': 7926.081, 'Speed': 127.0},
 {'Time_sec': 15.985, 'X': 696.0, 'Y': 7921.0, 'Speed': 127.0},
 {'Time_sec': 16.11, 'X': 737.123, 'Y': 7904.166, 'Speed': 127.0},
 {'Time_sec': 16.205, 'X': 769.0, 'Y': 7893.0, 'Speed': 130.56},
 {'Time_sec': 16.305, 'X': 803.0, 'Y': 7883.0, 'Speed': 134.31},
 {'Time_sec': 16.35, 'X': 818.953, 'Y': 7879.165, 'Speed': 136.0},
 {'Time_sec': 16.51, 'X': 879.13, 'Y': 7868.962, 'Speed': 136.0},
 {'Time_sec': 16.585, 'X': 908.0, 'Y': 7866.0, 'Speed': 136.8},
 {'Time_sec': 16.79, 'X': 987.252, 'Y': 7863.817, 'Speed': 139.0},
 {'Time_sec': 16.805, 'X': 993.0, 'Y': 7864.0, 'Speed': 139.31},
 {'Time_sec': 16.985, 'X': 1065.0, 'Y': 7870.0, 'Speed': 143.06},
 {'Time_sec': 17.03, 'X': 1086.661, 'Y': 7872.705, 'Speed': 144.0},
 {'Time_sec': 17.285, 'X': 1220.0, 'Y': 7893.0, 'Speed': 147.97},
 {'Time_sec': 17.351, 'X': 1244.287, 'Y': 7897.251, 'Speed': 149.0},
 {'Time_sec': 17.55, 'X': 1298.31, 'Y': 7908.444, 'Speed': 149.0},
 {'Time_sec': 17.585, 'X': 1310.0, 'Y': 7911.0, 'Speed': 150.17},
 {'Time_sec': 17.805, 'X': 1402.0, 'Y': 7932.0, 'Speed': 157.5},
 {'Time_sec': 17.91, 'X': 1447.722, 'Y': 7944.07, 'Speed': 161.0},
 {'Time_sec': 18.11, 'X': 1534.426, 'Y': 7969.936, 'Speed': 165.0},
 {'Time_sec': 18.125, 'X': 1541.0, 'Y': 7972.0, 'Speed': 165.5},
 {'Time_sec': 18.345, 'X': 1639.0, 'Y': 8004.0, 'Speed': 172.83},
 {'Time_sec': 18.47, 'X': 1696.58, 'Y': 8022.972, 'Speed': 177.0},
 {'Time_sec': 18.505, 'X': 1713.0, 'Y': 8028.0, 'Speed': 177.0},
 {'Time_sec': 18.63, 'X': 1772.755, 'Y': 8044.256, 'Speed': 177.0},
 {'Time_sec': 18.725, 'X': 1819.0, 'Y': 8054.0, 'Speed': 177.0},
 {'Time_sec': 18.87, 'X': 1890.535, 'Y': 8063.567, 'Speed': 177.0},
 {'Time_sec': 18.925, 'X': 1918.0, 'Y': 8066.0, 'Speed': 177.0},
 {'Time_sec': 19.165, 'X': 2039.0, 'Y': 8071.0, 'Speed': 177.0},
 {'Time_sec': 19.19, 'X': 2051.426, 'Y': 8071.069, 'Speed': 177.0},
 {'Time_sec': 19.365, 'X': 2147.0, 'Y': 8069.0, 'Speed': 192.86},
 {'Time_sec': 19.51, 'X': 2263.892, 'Y': 8063.143, 'Speed': 206.0},
 {'Time_sec': 19.585, 'X': 2319.0, 'Y': 8060.0, 'Speed': 212.09},
 {'Time_sec': 19.67, 'X': 2366.289, 'Y': 8057.087, 'Speed': 219.0},
 {'Time_sec': 19.945, 'X': 2491.0, 'Y': 8043.0, 'Speed': 225.88},
 {'Time_sec': 20.11, 'X': 2647.164, 'Y': 8019.532, 'Speed': 230.0},
 {'Time_sec': 20.145, 'X': 2681.0, 'Y': 8014.0, 'Speed': 230.88},
 {'Time_sec': 20.47, 'X': 2938.317, 'Y': 7963.107, 'Speed': 239.0},
 {'Time_sec': 20.604, 'X': 3008.0, 'Y': 7948.0, 'Speed': 242.35},
 {'Time_sec': 20.63, 'X': 3018.784, 'Y': 7945.702, 'Speed': 243.0},
 {'Time_sec': 20.904, 'X': 3116.0, 'Y': 7926.0, 'Speed': 247.57},
 {'Time_sec': 20.99, 'X': 3169.856, 'Y': 7915.232, 'Speed': 249.0},
 {'Time_sec': 21.185, 'X': 3321.0, 'Y': 7885.0, 'Speed': 252.48},
 {'Time_sec': 21.27, 'X': 3380.742, 'Y': 7873.059, 'Speed': 254.0},
 {'Time_sec': 21.365, 'X': 3446.0, 'Y': 7860.0, 'Speed': 255.78},
 {'Time_sec': 21.43, 'X': 3492.527, 'Y': 7850.663, 'Speed': 257.0},
 {'Time_sec': 21.625, 'X': 3628.0, 'Y': 7823.0, 'Speed': 259.12},
 {'Time_sec': 21.725, 'X': 3684.0, 'Y': 7811.0, 'Speed': 260.21},
 {'Time_sec': 22.045, 'X': 3912.0, 'Y': 7765.0, 'Speed': 263.68},
 {'Time_sec': 22.285, 'X': 4114.0, 'Y': 7724.0, 'Speed': 266.29},
 {'Time_sec': 22.35, 'X': 4166.496, 'Y': 7713.564, 'Speed': 267.0},
 {'Time_sec': 22.585, 'X': 4358.0, 'Y': 7676.0, 'Speed': 269.94},
 {'Time_sec': 22.67, 'X': 4439.075, 'Y': 7659.775, 'Speed': 271.0},
 {'Time_sec': 22.91, 'X': 4673.208, 'Y': 7612.378, 'Speed': 271.0},
 {'Time_sec': 22.925, 'X': 4685.0, 'Y': 7610.0, 'Speed': 271.27},
 {'Time_sec': 23.19, 'X': 4832.552, 'Y': 7580.618, 'Speed': 276.0},
 {'Time_sec': 23.325, 'X': 4912.0, 'Y': 7565.0, 'Speed': 277.69},
 {'Time_sec': 23.43, 'X': 4990.713, 'Y': 7549.526, 'Speed': 279.0},
 {'Time_sec': 23.505, 'X': 5050.0, 'Y': 7538.0, 'Speed': 279.63},
 {'Time_sec': 23.67, 'X': 5176.393, 'Y': 7514.029, 'Speed': 281.0},
 {'Time_sec': 23.745, 'X': 5234.0, 'Y': 7503.0, 'Speed': 281.7},
 {'Time_sec': 23.845, 'X': 5311.0, 'Y': 7488.0, 'Speed': 282.64},
 {'Time_sec': 23.991, 'X': 5411.168, 'Y': 7468.699, 'Speed': 284.0},
 {'Time_sec': 24.185, 'X': 5574.0, 'Y': 7438.0, 'Speed': 284.0},
 {'Time_sec': 24.35, 'X': 5784.656, 'Y': 7398.572, 'Speed': 284.0},
 {'Time_sec': 24.385, 'X': 5820.0, 'Y': 7392.0, 'Speed': 281.37},
 {'Time_sec': 24.685, 'X': 5952.0, 'Y': 7368.0, 'Speed': 258.88},
 {'Time_sec': 24.75, 'X': 5993.318, 'Y': 7360.246, 'Speed': 254.0},
 {'Time_sec': 24.845, 'X': 6064.0, 'Y': 7347.0, 'Speed': 251.84},
 {'Time_sec': 25.085, 'X': 6241.0, 'Y': 7315.0, 'Speed': 246.39},
 {'Time_sec': 25.19, 'X': 6344.207, 'Y': 7296.381, 'Speed': 244.0},
 {'Time_sec': 25.365, 'X': 6518.0, 'Y': 7265.0, 'Speed': 242.13},
 {'Time_sec': 25.47, 'X': 6586.387, 'Y': 7252.73, 'Speed': 241.0},
 {'Time_sec': 25.75, 'X': 6692.848, 'Y': 7233.362, 'Speed': 213.0},
 {'Time_sec': 25.765, 'X': 6700.0, 'Y': 7232.0, 'Speed': 211.84},
 {'Time_sec': 25.905, 'X': 6778.0, 'Y': 7217.0, 'Speed': 200.99},
 {'Time_sec': 26.15, 'X': 6949.636, 'Y': 7184.334, 'Speed': 182.0},
 {'Time_sec': 26.205, 'X': 6981.0, 'Y': 7178.0, 'Speed': 179.94},
 {'Time_sec': 26.31, 'X': 7026.664, 'Y': 7168.012, 'Speed': 176.0},
 {'Time_sec': 26.585, 'X': 7103.0, 'Y': 7145.0, 'Speed': 156.23},
 {'Time_sec': 26.63, 'X': 7119.841, 'Y': 7139.398, 'Speed': 153.0},
 {'Time_sec': 26.725, 'X': 7158.0, 'Y': 7126.0, 'Speed': 147.78},
 {'Time_sec': 26.83, 'X': 7197.172, 'Y': 7109.798, 'Speed': 142.0},
 {'Time_sec': 26.985, 'X': 7250.0, 'Y': 7084.0, 'Speed': 138.12},
 {'Time_sec': 26.99, 'X': 7251.645, 'Y': 7083.148, 'Speed': 138.0},
 {'Time_sec': 27.164, 'X': 7306.0, 'Y': 7053.0, 'Speed': 133.65},
 {'Time_sec': 27.19, 'X': 7313.41, 'Y': 7048.485, 'Speed': 133.0},
 {'Time_sec': 27.404, 'X': 7371.0, 'Y': 7006.0, 'Speed': 120.77},
 {'Time_sec': 27.47, 'X': 7390.833, 'Y': 6986.944, 'Speed': 117.0},
 {'Time_sec': 27.645, 'X': 7441.0, 'Y': 6932.0, 'Speed': 112.63},
 {'Time_sec': 27.83, 'X': 7464.954, 'Y': 6898.952, 'Speed': 108.0},
 {'Time_sec': 27.985, 'X': 7475.0, 'Y': 6866.0, 'Speed': 105.67},
 {'Time_sec': 28.23, 'X': 7493.484, 'Y': 6771.266, 'Speed': 102.0},
 {'Time_sec': 28.285, 'X': 7496.0, 'Y': 6754.0, 'Speed': 101.66},
 {'Time_sec': 28.39, 'X': 7498.066, 'Y': 6730.903, 'Speed': 101.0},
 {'Time_sec': 28.55, 'X': 7496.439, 'Y': 6709.226, 'Speed': 99.0},
 {'Time_sec': 28.585, 'X': 7496.0, 'Y': 6703.0, 'Speed': 99.13},
 {'Time_sec': 28.83, 'X': 7491.459, 'Y': 6640.379, 'Speed': 100.0},
 {'Time_sec': 28.905, 'X': 7487.0, 'Y': 6614.0, 'Speed': 100.75},
 {'Time_sec': 29.03, 'X': 7474.904, 'Y': 6562.377, 'Speed': 102.0},
 {'Time_sec': 29.125, 'X': 7465.0, 'Y': 6526.0, 'Speed': 102.59},
 {'Time_sec': 29.19, 'X': 7459.136, 'Y': 6506.21, 'Speed': 103.0},
 {'Time_sec': 29.43, 'X': 7441.822, 'Y': 6462.437, 'Speed': 105.0},
 {'Time_sec': 29.545, 'X': 7430.0, 'Y': 6439.0, 'Speed': 109.31},
 {'Time_sec': 29.67, 'X': 7412.847, 'Y': 6406.309, 'Speed': 114.0},
 {'Time_sec': 29.785, 'X': 7393.0, 'Y': 6373.0, 'Speed': 117.29},
 {'Time_sec': 29.865, 'X': 7378.0, 'Y': 6351.0, 'Speed': 119.57},
 {'Time_sec': 29.95, 'X': 7368.89, 'Y': 6336.982, 'Speed': 122.0},
 {'Time_sec': 30.11, 'X': 7355.267, 'Y': 6318.709, 'Speed': 122.0},
 {'Time_sec': 30.125, 'X': 7352.0, 'Y': 6315.0, 'Speed': 122.6},
 {'Time_sec': 30.31, 'X': 7284.149, 'Y': 6241.424, 'Speed': 130.0},
 {'Time_sec': 30.385, 'X': 7258.0, 'Y': 6214.0, 'Speed': 131.49},
 {'Time_sec': 30.511, 'X': 7228.616, 'Y': 6184.795, 'Speed': 134.0},
 {'Time_sec': 30.725, 'X': 7193.0, 'Y': 6155.0, 'Speed': 146.48},
 {'Time_sec': 30.751, 'X': 7186.542, 'Y': 6149.583, 'Speed': 148.0},
 {'Time_sec': 30.91, 'X': 7136.613, 'Y': 6107.659, 'Speed': 148.0},
 {'Time_sec': 31.005, 'X': 7103.0, 'Y': 6081.0, 'Speed': 154.33},
 {'Time_sec': 31.15, 'X': 7050.054, 'Y': 6042.22, 'Speed': 164.0},
 {'Time_sec': 31.205, 'X': 7030.0, 'Y': 6028.0, 'Speed': 164.92},
 {'Time_sec': 31.39, 'X': 6960.369, 'Y': 5979.343, 'Speed': 168.0},
 {'Time_sec': 31.425, 'X': 6944.0, 'Y': 5968.0, 'Speed': 169.83},
 {'Time_sec': 31.665, 'X': 6811.0, 'Y': 5876.0, 'Speed': 182.38},
 {'Time_sec': 31.83, 'X': 6754.686, 'Y': 5836.348, 'Speed': 191.0},
 {'Time_sec': 31.985, 'X': 6708.0, 'Y': 5802.0, 'Speed': 196.04},
 {'Time_sec': 32.225, 'X': 6603.0, 'Y': 5723.0, 'Speed': 203.84},
 {'Time_sec': 32.23, 'X': 6600.836, 'Y': 5721.371, 'Speed': 204.0},
 {'Time_sec': 32.385, 'X': 6530.0, 'Y': 5667.0, 'Speed': 207.88},
 {'Time_sec': 32.55, 'X': 6409.548, 'Y': 5567.555, 'Speed': 212.0},
 {'Time_sec': 32.625, 'X': 6358.0, 'Y': 5524.0, 'Speed': 213.88},
 {'Time_sec': 32.87, 'X': 6259.094, 'Y': 5436.483, 'Speed': 220.0},
 {'Time_sec': 33.085, 'X': 6191.0, 'Y': 5361.0, 'Speed': 225.37},
 {'Time_sec': 33.27, 'X': 6100.512, 'Y': 5251.937, 'Speed': 230.0},
 {'Time_sec': 33.43, 'X': 6017.046, 'Y': 5148.031, 'Speed': 233.0},
 {'Time_sec': 33.505, 'X': 5988.0, 'Y': 5111.0, 'Speed': 233.27},
 {'Time_sec': 33.71, 'X': 5941.707, 'Y': 5048.111, 'Speed': 234.0},
 {'Time_sec': 33.864, 'X': 5906.0, 'Y': 4995.0, 'Speed': 229.19},
 {'Time_sec': 33.87, 'X': 5904.14, 'Y': 4992.238, 'Speed': 229.0},
 {'Time_sec': 33.984, 'X': 5864.0, 'Y': 4932.0, 'Speed': 224.44},
 {'Time_sec': 34.07, 'X': 5833.17, 'Y': 4882.891, 'Speed': 221.0},
 {'Time_sec': 34.205, 'X': 5787.0, 'Y': 4806.0, 'Speed': 216.28},
 {'Time_sec': 34.27, 'X': 5766.454, 'Y': 4771.689, 'Speed': 214.0},
 {'Time_sec': 34.47, 'X': 5708.236, 'Y': 4675.545, 'Speed': 202.0},
 {'Time_sec': 34.525, 'X': 5692.0, 'Y': 4650.0, 'Speed': 199.25},
 {'Time_sec': 34.63, 'X': 5660.2, 'Y': 4601.751, 'Speed': 194.0},
 {'Time_sec': 34.745, 'X': 5626.0, 'Y': 4553.0, 'Speed': 191.12},
 {'Time_sec': 34.87, 'X': 5591.317, 'Y': 4508.326, 'Speed': 188.0},
 {'Time_sec': 34.905, 'X': 5581.0, 'Y': 4496.0, 'Speed': 186.98},
 {'Time_sec': 35.11, 'X': 5512.217, 'Y': 4421.223, 'Speed': 181.0},
 {'Time_sec': 35.125, 'X': 5507.0, 'Y': 4416.0, 'Speed': 180.63},
 {'Time_sec': 35.305, 'X': 5442.0, 'Y': 4357.0, 'Speed': 176.12},
 {'Time_sec': 35.43, 'X': 5387.264, 'Y': 4316.67, 'Speed': 173.0},
 {'Time_sec': 35.585, 'X': 5319.0, 'Y': 4273.0, 'Speed': 169.61},
 {'Time_sec': 35.75, 'X': 5263.524, 'Y': 4243.579, 'Speed': 166.0},
 {'Time_sec': 35.865, 'X': 5220.0, 'Y': 4228.0, 'Speed': 165.04},
 {'Time_sec': 36.11, 'X': 5089.022, 'Y': 4198.048, 'Speed': 163.0},
 {'Time_sec': 36.185, 'X': 5052.0, 'Y': 4192.0, 'Speed': 163.0},
 {'Time_sec': 36.505, 'X': 4933.0, 'Y': 4185.0, 'Speed': 163.0},
 {'Time_sec': 36.51, 'X': 4931.067, 'Y': 4184.988, 'Speed': 163.0},
 {'Time_sec': 36.71, 'X': 4843.871, 'Y': 4185.34, 'Speed': 165.0},
 {'Time_sec': 36.785, 'X': 4802.0, 'Y': 4186.0, 'Speed': 166.36},
 {'Time_sec': 37.005, 'X': 4661.0, 'Y': 4189.0, 'Speed': 170.35},
 {'Time_sec': 37.151, 'X': 4606.443, 'Y': 4189.594, 'Speed': 173.0},
 {'Time_sec': 37.285, 'X': 4564.0, 'Y': 4189.0, 'Speed': 174.67},
 {'Time_sec': 37.311, 'X': 4553.71, 'Y': 4188.779, 'Speed': 175.0},
 {'Time_sec': 37.471, 'X': 4476.101, 'Y': 4185.862, 'Speed': 178.0},
 {'Time_sec': 37.525, 'X': 4445.0, 'Y': 4183.0, 'Speed': 179.35},
 {'Time_sec': 37.75, 'X': 4295.089, 'Y': 4159.056, 'Speed': 185.0},
 {'Time_sec': 37.845, 'X': 4242.0, 'Y': 4148.0, 'Speed': 186.19},
 {'Time_sec': 37.99, 'X': 4186.791, 'Y': 4133.48, 'Speed': 188.0},
 {'Time_sec': 38.165, 'X': 4132.0, 'Y': 4113.0, 'Speed': 189.94},
 {'Time_sec': 38.35, 'X': 4046.715, 'Y': 4078.331, 'Speed': 192.0},
 {'Time_sec': 38.485, 'X': 3976.0, 'Y': 4043.0, 'Speed': 192.84},
 {'Time_sec': 38.51, 'X': 3962.797, 'Y': 4035.417, 'Speed': 193.0},
 {'Time_sec': 38.79, 'X': 3812.623, 'Y': 3928.295, 'Speed': 198.0},
 {'Time_sec': 38.99, 'X': 3702.846, 'Y': 3826.936, 'Speed': 200.0},
 {'Time_sec': 39.31, 'X': 3559.342, 'Y': 3677.078, 'Speed': 206.0},
 {'Time_sec': 39.465, 'X': 3512.0, 'Y': 3622.0, 'Speed': 209.39},
 {'Time_sec': 39.63, 'X': 3477.501, 'Y': 3575.925, 'Speed': 213.0},
 {'Time_sec': 39.79, 'X': 3446.164, 'Y': 3527.281, 'Speed': 216.0},
 {'Time_sec': 39.825, 'X': 3437.0, 'Y': 3513.0, 'Speed': 216.49},

In [6]:
import json
with open("data.js", "w") as f:
    f.write("const data = `")
    json.dump(data, f)
    f.write("`;")
    f.write("export default data;")